Upload complete: 19321 KiB in 472 ms (40934 KiB/s)

*** Upgrading Firmware ***
*** Data: 19784478 (0x12de31e) bytes at 0x460000d0 ***

UBI partition 'ubi' already selected
Volume fit not found!
Volume rootfs_data not found!
Updating volume 'kernel' from 0x460008d0, size 0x443ad8 ... "Error" handler, esr 0xbf000001
elr: 0000000041e71d0c lr : 0000000041e2e404 (reloc)
elr: 000000005ff94d0c lr : 000000005ff51404
x0 : 000000005fb25600 x1 : 000000005fb923c0
x2 : 0000000000000800 x3 : 00000000000003f0
x4 : 64ad52bef210c88c x5 : 0000000000000000
x6 : 00000000000000ff x7 : 000000005fba8bc0
x8 : 000000005f7fec10 x9 : 000000005fb25280
x10: 0000000001a49800 x11: 00000000ffffffff
x12: 00000000ffffffff x13: 0000000000000200
x14: 000000005f7fea97 x15: 000000005f7fee79
x16: 000000005ff6d370 x17: 000000001c2ae96c
x18: 000000005f7ffdd0 x19: 0000000000000000
x20: 000000005fb25140 x21: 000000005fb25280
x22: 000000005f7feb80 x23: 0000000000000800
x24: 000000005fb25140 x25: 0000000000000000
x26: 0000000000000040 x27: 0000000000000000
x28: 0000000001a49800 x29: 000000005f7feaa0

Code: d65f03c0 f8636824 f8236804 91002063 (cb030044)
Resetting CPU ...

resetting ...

F0: 102B 0000
FA: 1040 0000
FA: 1040 0000 [0200]
F9: 0000 0000
V0: 0000 0000 [0001]
00: 0000 0000
BP: 2400 0041 [0000]
G0: 1190 0000
EC: 0000 0000 [1000]
T0: 0000 0256 [010F]
Jump to BL

NOTICE:  BL2: v2.13.0(release):2026.08.31-1437-all-30-g4d5f0ffe0-dirty
NOTICE:  BL2: Built : 21:22:58, Sep 17 2026
NOTICE:  WDT: [40000000] Software reset (reboot)
NOTICE:  EMI: Using DDR3 settings
NOTICE:  measure value is unexpected
NOTICE:  EMI: Detected DRAM size: 512MB
NOTICE:  EMI: complex R/W mem test passed
NOTICE:  CPU: MT7981 (1700MHz)
WARNING: CASN page may not exist. Try to read parameter page.
INFO:    PP COPY 0 CRC read: 0x1ccd, compute: 0x1ccd
NOTICE:  SPI_NAND parses attributes from parameter page.
NOTICE:  SPI_NAND Detected ID 0xc8
NOTICE:  Page size 2048, Block size 131072, size 134217728
NOTICE:  Initializing NMBM ...
NOTICE:  Signature found at block 1023 [0x07fe0000]
NOTICE:  First info table with writecount 0 found in block 976
NOTICE:  Second info table with writecount 0 found in block 979
NOTICE:  NMBM has been successfully attached in read-only mode
INFO:    BL2: Doing platform setup
INFO:    BL2: Loading image id 3
INFO:    Loading image id=3 at address 0x40800000
INFO:    Image id=3 loaded: 0x40800000 - 0x4080b29c
INFO:    BL2: Loading image id 5
INFO:    Loading image id=5 at address 0x40800000
INFO:    Image id=5 loaded: 0x40800000 - 0x408ddd38
NOTICE:  BL2: Booting BL31
INFO:    Entry point address = 0x43001000
INFO:    SPSR = 0x3cd
INFO:    Total CPU count: 2
INFO:    MCUSYS: L2C share 256K --> 0K
INFO:    Disable NETSYS SRAM remapping
INFO:    SPMC: Changed to SPMC mode
NOTICE:  BL31: v2.13.0(release):2026.08.31-1437-all-31-g6dcad3adc
NOTICE:  BL31: Built : 06:27:11, Sep 17 2026
INFO:    [DEVAPC] devapc_init done
INFO:    [MPU](Region0)sa:0x0300, ea:0x0301
INFO:    [MPU](Region0)apc0:0x80b6db69, apc1:0x00b6db6d
INFO:    [MPU](Region1)sa:0x0000, ea:0x0000
INFO:    [MPU](Region1)apc0:0x00000000, apc1:0x00000000
INFO:    [MPU](Region2)sa:0x0000, ea:0x0000
INFO:    [MPU](Region2)apc0:0x00000000, apc1:0x00000000
INFO:    [MPU](Region3)sa:0x0000, ea:0x0000
INFO:    [MPU](Region3)apc0:0x00000000, apc1:0x00000000
INFO:    GICv3 without legacy support detected.
INFO:    ARM GICv3 driver initialized in EL3
INFO:    Maximum SPI INTID supported: 671
INFO:    BL31: Initializing runtime services
INFO:    Secondary bootloader is AArch64
INFO:    BL31: Preparing for EL3 exit to normal world
INFO:    Entry point address = 0x41e00000
INFO:    SPSR = 0x3c9


U-Boot 2025.07.1010-Mediatek (Sep 17 2026 - 06:26:42 +0800)

CPU:   MediaTek MT7981
Model: mt7981-qihoo-360t7
       (mediatek,mt7981-rfb)
DRAM:  512 MiB
Core:  29 devices, 16 uclasses, devicetree: embed
Loading Environment from MTD... spi-nand: spi_nand spi_nand@0: CASN page check failed
spi-nand: spi_nand spi_nand@0: Your SPI NAND might not support CASN, or the CASN page is corrupted.
spi-nand: spi_nand spi_nand@0: Fallback to read ID
spi-nand: spi_nand spi_nand@0: ESMT SPI NAND was found.
spi-nand: spi_nand spi_nand@0: 128 MiB, block size: 128 KiB, page size: 2048, OOB size: 64
Could not find a valid device for nmbm0
*** Warning - get_mtd_device_nm() failed, using default environment


Initializing NMBM ...
Signature found at block 1023 [0x07fe0000]
First info table with writecount 0 found in block 976
Second info table with writecount 0 found in block 979
NMBM has been successfully attached

Loading Environment from MTD... OK
Loading Environment from MTD... OK
In:    serial@11002000
Out:   serial@11002000
Err:   serial@11002000
Net:   MediaTek MT7531
eth0: ethernet@15100000
glbtn: checking reset
glbtn: no configured key is pressed (use 'glbtn help' for setup)
netabort: check enabled (UDP port 37541)
netabort: waiting for trigger, key to skip:  0

    *** U-Boot Boot Menu ***

      1. Startup system (Default)
      2. Upgrade firmware
      3. Upgrade ATF BL2
      4. Upgrade ATF FIP
      5. Upgrade single image
      6. Load image
      7. Start Web failsafe
      8. Change boot configuration
      0. Exit


  Press UP/DOWN to move, ENTER to select, ESC to quit
ubi0: attaching mtd6
ubi0: scanning is finished
ubi0: attached mtd6 (name "ubi", size 108 MiB)
ubi0: PEB size: 131072 bytes (128 KiB), LEB size: 126976 bytes
ubi0: min./max. I/O unit sizes: 2048/2048, sub-page size 2048
ubi0: VID header offset: 2048 (aligned 2048), data offset: 4096
ubi0: good PEBs: 864, bad PEBs: 0, corrupted PEBs: 0
ubi0: user volume: 2, internal volumes: 1, max. volumes count: 128
ubi0: max/mean erase counter: 4/2, WL threshold: 4096, image sequence number: 0
ubi0: available PEBs: 683, total reserved PEBs: 181, PEBs reserved for bad PEB handling: 20
damaged volume, update marker is setVolume fit not found!

Web failsafe UI started
URL: http://192.168.1.1/
Press Ctrl+C to exit
dnsd: started, resolving 'failsafe.lan' -> 192.168.1.1
